baseurl: /oniripolis-staging
url: http://adamselene.github.io/oniripolis-staging
encoding: UTF-8
exclude:
- ".gitignore"
- ".gitattributes"
- "CNAME"
- "LICENSE"
- "README.md"
gems:
  - jekyll-sitemap
